version: "3.8"
secrets:
  tezos-ci-token:
    external: true
  tezos-ci-webhook-secret:
    external: true
  tezos-ci-submission-cap:
    external: true
networks:
  infra_default:
    external: true
services:
  ci:
    image: ocurrent/tezos-ci:live
    command: --ocluster-cap /run/secrets/tezos-ci-submission-cap --gitlab-token-file /run/secrets/tezos-ci-token --gitlab-webhook-secret-file /run/secrets/tezos-ci-webhook-secret
    ports:
      - '8080:8080'
    environment:
      - "CI_PROFILE=production"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    volumes:
      - 'data:/var/lib/ocurrent'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'tezos-ci-token'
      - 'tezos-ci-webhook-secret'
      - 'tezos-ci-submission-cap'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
    networks:
      - infra_default
volumes:
  data:
  capnp-secrets:
